kind: Service
apiVersion: v1
metadata:
  name: lc-web  # The name of your service
spec:
  selector:
    app: lc-web  # defines how the Service finds which Pods to target
  ports:
  - protocol: TCP
    port: 80 # The service port
    targetPort: 80 # The pods port